package me.bannock.capstone.backend.security;

public enum Privilege {

    PRIV_LOGIN("PRIV_LOGIN"),
    PRIV_VIEW_MAIN_APP_PANEL("PRIV_VIEW_MAIN_APP_PANEL"),
    PRIV_VIEW_ADMIN_PANEL("PRIV_VIEW_ADMIN_PANEL"),
    PRIV_LAUNCH_LOADER("PRIV_LAUNCH_LOADER"),
    PRIV_MANAGE_USER_PRIVS("PRIV_MANAGE_USER_PRIVS"),
    PRIV_VIEW_USER_PRIVS("PRIV_VIEW_USER_PRIVS"),
    PRIV_VIEW_OWN_PRIVS("PRIV_VIEW_OWN_PRIVS"),
    PRIV_REGISTER_PRODUCT("PRIV_REGISTER_PRODUCT"),
    PRIV_MODIFY_PRODUCT_DETAILS("PRIV_MODIFY_PRODUCT_DETAILS"),
    PRIV_VIEW_OWN_PRODUCTS("PRIV_VIEW_OWN_PRODUCTS"),
    PRIV_CREATE_LICENSE("PRIV_CREATE_LICENSE"),
    PRIV_BAN_OWN_PRODUCT_LICENSES("PRIV_BAN_OWN_PRODUCT_LICENSES"),
    PRIV_UNBAN_OWN_PRODUCT_LICENSES("PRIV_UNBAN_OWN_PRODUCT_LICENSES"),
    PRIV_BAN_ANY_LICENSE("PRIV_BAN_ANY_LICENSE"),
    PRIV_UNBAN_ANY_LICENSE("PRIV_UNBAN_ANY_LICENSE"),
    PRIV_ACTIVATE_LICENSE("PRIV_ACTIVATE_LICENSE"),
    PRIV_GET_LICENSES("PRIV_GET_LICENSES"),
    PRIV_USE_OWN_LICENSES("PRIV_USE_OWN_LICENSES"),
    PRIV_DEACTIVATE_LICENSE("PRIV_DEACTIVATE_LICENSE"),
    PRIV_DELETE_LICENSE("PRIV_DELETE_LICENSE"),
    PRIV_USE_API("PRIV_USE_API"),
    PRIV_VIEW_API_KEY("PRIV_VIEW_API_KEY"),
    PRIV_VIEW_OWN_ACCOUNT_INFORMATION("PRIV_VIEW_OWN_ACCOUNT_INFORMATION"),
    PRIV_UPDATE_OWN_HWID("PRIV_UPDATE_OWN_HWID"),
    PRIV_UPDATE_USER_HWIDS("PRIV_UPDATE_USER_HWIDS"),
    PRIV_RESET_HWID("PRIV_RESET_HWID");

    /**
     * @param privilege The privilege
     */
    Privilege(String privilege){
        this.privilege = privilege;
    }

    private final String privilege;

    public String getPrivilege() {
        return privilege;
    }
}
